### ISSUE TITLE
Get "Dev Tool #1", "Dev Tool #2" buttons visible on front page also when users are not logged in

### ISSUE THREAD

**Issue by timirnich** [SUSE-Developer-Community/explore.suse.dev#19]
Currently these buttons are only visible to logged in users and I think we should also have them visible on the "unregistered" home page.

**Comment by feri** [comment]
I agree.

**Comment by feri** [comment]
The fix has to be done in the theme. Will do it right away.

**Comment by feri** [comment]
I was wrong. The featured boxes can be enabled in the theme settings. I have turned them on. We need to add content and links.
