### ISSUE TITLE
Footer changes

### ISSUE THREAD

**Issue by feri** [SUSE-Developer-Community/explore.suse.dev#23]
As discussed it would be nice to have another footer area too where we'd accommodate various links and call to actions. This would be above the standard corporate footer, and the links and content would be relevant to the dev portal.

**Comment by timirnich** [comment]
Do we need two footers or can we just change the existing one to look the way we want it?

**Comment by feri** [comment]
Yes, good point! I think we'd better off with one footer. Agree.

**Comment by feri** [comment]
Done.
