### ISSUE TITLE
Feedback / issue integration 

### ISSUE THREAD

**Issue by feri** [SUSE-Developer-Community/explore.suse.dev#24]
It might be nice if people could give us feedback on the devportal directly, instead of navigating away to github, or somewhere else. We could do a smart integration where we capture feedback (including perhaps a name, and email, unless the user is authenticated) and send that data to the desired end point, like github.

**Comment by timirnich** [comment]
As a temporary workaround / first step towards that end goal, could we do a simple feedback form that sends an email to developers@suse.com for now? Sarah told me she doesn't want issue reports to end up in the forum which makes sense to me...

**Comment by timirnich** [comment]
Thought a bit more about this. I believe we need two different mechanisms for feedback. The first one is for questions/comments/suggestions and related discussions, we will want to land those in the forum. The other one is for issues ("I need my password reset") and that would be better to land in some sort of ticket tracker (or in the developer@suse.com mailbox for the time being). 
So a "report an issue" link to a feedback form that triggers an email and a "Ask a question" link to the forum seems to be the way to do this. Makes sense?

**Comment by feri** [comment]
Yes, I agree, we need separate mechanisms.

We can send emails to the dev mailbox and sort them based on subject. That's easy. 

Issues can also be added to appropriate github projects automatically. We have projects for the portal, the getting started guide, the python hello world and some other. We don't have an issue tracker for the CAP sandbox itself. We could either collect the sandbox issues under the portal project (and tag them properly) or we could create a separate project just for the issues.

**Comment by timirnich** [comment]
> We don't have an issue tracker for the CAP sandbox itself. We could either collect the sandbox issues under the portal project (and tag them properly) or we could create a separate project just for the issues.

We have the repo for the onboarding app which we can use as an issue tracker for the sandbox.

**Comment by feri** [comment]
OK, great.

**Comment by agracey** [comment]
Do you think we can call this good?
