### ISSUE TITLE
Decide what to do with the main menu bar

### ISSUE THREAD

**Issue by timirnich** [SUSE-Developer-Community/explore.suse.dev#26]
Should we keep the main menu bar (and have it point to pages discussing different angles of the sandbox) or should we get rid of it altogether (for now)?

**Comment by feri** [comment]
I think if we keep it, then we must have different topics, not just the sandbox and its angles. People will wonder if this portal is only for CAP. 

As time goes we will have more content covering a range of topics. Making those articles accessible via that main menu would make sense. 

Hiding would be probably the better choice now. However there will be a large blank space and not sure how could we fill that up.

**Comment by feri** [comment]
I am closing this since we found a solution.
