### ISSUE TITLE
Branding for SUSE

### ISSUE THREAD

**Issue by agracey** [SUSE-Developer-Community/explore.suse.dev#3]

**Comment by feri** [comment]
We are getting help from UI / UX teams. Will move on with this as soon as design / CSS is received.

**Comment by feri** [comment]
Thanks to the design team we got the 1st mockups:

**Comment by feri** [comment]
Thanks to the deisgn team we got the 1st mockups: 
![Landing](https://user-images.githubusercontent.com/232490/75562292-ff941600-5a50-11ea-9df1-6b536d13dfad.png)
![Article](https://user-images.githubusercontent.com/232490/75562329-12a6e600-5a51-11ea-9459-7abbb04f44bf.png)

**Comment by feri** [comment]
Header and footer have been done. The front page and the articles would require a separate template.

**Comment by feri** [comment]
Do we still want more styling based on the original design we received?

**Comment by agracey** [comment]
Closing since this is done
