### ISSUE TITLE
Newly created account can't login

### ISSUE THREAD

**Issue by Firstyear** [SUSE-Developer-Community/explore.suse.dev#49]
Hi,

I signed up for a developer account with my email. The details are shown here:

![Screen Shot 2020-04-24 at 09 50 41](https://user-images.githubusercontent.com/271005/80160480-169a5300-8611-11ea-9daf-f000643fe703.png)

I then attempt to login to https://stratos.cap.explore.suse.dev/login and it fails:

![Screen Shot 2020-04-24 at 09 48 13](https://user-images.githubusercontent.com/271005/80160499-25810580-8611-11ea-809e-25bc79c6ab4e.png)

I can also confirm that this fails with the cf-cli as well:

```
> cf login -a https://api.cap.explore.suse.dev -u wbrown@suse.de -p XXX...

API endpoint: https://api.cap.explore.suse.dev

Authenticating...
Credentials were rejected, please try again.
```

I have confirmed and checked that the password is correct. Some details:

* I was never asked for a "username" to sign up
* The login form to stratos should request a username *or* email to be clearer about what identifier is required. 

Update: 

I think I found my username: It's located at https://www.explore.suse.dev/my-account/ but there is no way to get to this page unless you modify the url, no amount of clicking in the explore.suse.de site led me to this.

So I think that the username needs to be selected by the user at account creation time, and that all login elements should access username OR email as a unique id.

Even with using wbrown or @wbrown as a username I'm still not able to access the developer resources, so I think that some improvements to the account creation workflow are required.

PS: I'm willing to advise on this as I'm an employee of SUSE Labs, and I specialise in identity management. 

Thanks,

**Comment by timirnich** [comment]
Thanks, this is a very diligently written ticket! 

I'll take a look at the system to check what isn't working here. What is the username you selected when you requested your sandbox on https://www.explore.suse.dev/capsandbox/ after community registration?

**Comment by Firstyear** [comment]
Ahhhhhh I see what went wrong here.

When you aren't logged in, and you select the signup link here:

![Screen Shot 2020-04-24 at 22 55 44](https://user-images.githubusercontent.com/271005/80214798-c6f27080-867e-11ea-9693-b27a75051864.png)

This takes you to:

![Screen Shot 2020-04-24 at 22 56 38](https://user-images.githubusercontent.com/271005/80214858-e093b800-867e-11ea-97e8-8d9c202b6e9c.png)

At which point I selected "sign up" in the bottom right.

After that I never went *back* to the capsandbox page thinking that "well I had already signed up". It wasn't clear in that process you needed to come back and then get the username registered as well.

So maybe that part of the work flow needs to be clearer?

**Comment by Firstyear** [comment]
PS: Also it seems like the username rego on capsandbox wants an extra password? Shouldn't this be single sign on or similar? Anyway thanks for your time!

**Comment by timirnich** [comment]
Yeah I see that is a bit confusing. I'll try to come up with a way to clarify this better. 

We would have liked to make the Sandbox use SSO but unfortunately there's a technical limitation with Cloud Foundry that would have made CLI access essentially impossible at this stage. We're in contact with the product team to fix this but for now the only choice we had was to use separate credentials. It also has an advantage that one portal user can in fact have multiple sandboxes, which is a feature our colleagues in Sales and Pre-sales were requesting.

**Comment by Firstyear** [comment]
Hmmm that should certainly be more obvious in the UI then - it appeared that a developer account had a 1:1 to the sandbox, not that there was a 1:N relationship, and you could manage those seperately. Perhaps a tab in the my-accont listing your sandbox accounts with a +/- to add remove more by usernames? As well as improved steps on the quickstart? Is that a reasonable suggestion? Thanks!

**Comment by Firstyear** [comment]
Yeah that would be good to have this be a bit smoother, I can see this tripping people up, thanks for your time and letting me have this input!
