### ISSUE TITLE
Changing email address

### ISSUE THREAD

**Issue by megazone23** [SUSE-Developer-Community/explore.suse.dev#51]
Hi,

My company was acquired by another company and my email address has changed.  Right now all emails are being forwarded but I am not sure how long email forwards will work.  Is there any way to change the email?  I tried using the okta portal but it does not allow any changes.

**Comment by agracey** [comment]
Hi @megazone23,

Send us an email at developers(at) suse.com and we can help you out. 

As a heads up, it might take a little bit as we are in the middle of switching identity providers to join in with the rest of the external SUSE services. It might be that the new tooling that's being put in place with give you self service but if you email us we can get you to where you need to be!


Thank you,
Andrew Gracey

**Comment by feri** [comment]
https://www.suse.com/account/update/ allows you to update user info, except the email address. 
You will have to create a new account at https://www.suse.com/account. 

Our portal will switch to Okta in the coming days, so I'd recommend to do all changes at suse.com.
