### ISSUE TITLE
MariaDB service credentials do not contain a db name

### ISSUE THREAD

**Issue by spgreenberg** [SUSE-Developer-Community/explore.suse.dev#60]
The VCAP_SERVICES entry for mariadb instances do not contain the db name as part of the URI (or another credential value). This causes spring cloud applications, including spring-music, to fail. From the spring-music logs:

`com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'null'`

I believe the broker should provision and instance and create a db.

**Comment by spgreenberg** [comment]
Service keys are also missing a database name.

**Comment by spgreenberg** [comment]
Troy pointed me to this: https://documentation.suse.com/suse-cap/2.0/html/cap-guides/cha-cap-service-brokers.html#sec-cap-minibroker-application-usage denoting this is the expected behavior. 

Closing this issue.

**Comment by agracey** [comment]
@timirnich Is also looking at this. Which git repo are you pulling spring music from?

**Comment by troytop** [comment]
Docs are out of date (the upstream chart has changed its parameters). Passing this json to the broker should work: 
`{ "db": { "user": "admin", "name": "music" } }`

As per: https://github.com/helm/charts/tree/master/stable/mariadb#parameters

**Comment by spgreenberg** [comment]
https://github.com/scf-samples/spring-music.git

**Comment by timirnich** [comment]
@spgreenberg just out of curiosity, is there a particular reason you're using MariaDB with Spring Music? Since the readme says the app supports only mysql, postgres, mongodb and redis.

**Comment by troytop** [comment]
MySQL and MariaDB are almost completely compatible (and both work with this sample application). Only MariaDB is available in the CAP Sandbox though.

**Comment by timirnich** [comment]
@spgreenberg do you have what you needs with Troy's advice above? I ran into a few roadblocks with my own environment when I tried to reproduce this but I'm happy to dig in more if you still need help...
