### ISSUE TITLE
Issue with doing switch user remotely

### ISSUE THREAD

**Issue by deepamsehgal** [SUSE-Developer-Community/explore.suse.dev#69]
When we perform switch user/logout/login repeateldy from a remote accessing software, the Suse OS kills all processes, unmounts all users and goes to an inaccessible state, showing just a blank screen with a blinking cursor at 1,1. It needs manual reboot to come up again. Can someone please help in knowing why OS behaves like this?

**Comment by agracey** [comment]
This not a support channel, please contact your support person for suse products or the opensuse discord for questions about opensuse
