### ISSUE TITLE
New account result in `Requested route (...) does not exist` error

### ISSUE THREAD

**Issue by edwin-hendriks** [SUSE-Developer-Community/explore.suse.dev#72]
Just today I created an account. All is fine but one thing. The default app gives the error `404 Not Found: Requested route ('12factor_processacceleration_gmail_com.cap.explore.suse.dev') does not exist.`. 

Also creating / pushing new applications (using a proven approach that works for some friends of mine a week ago) resulted in the same error. 

I just tried again creating a new account and repeated the whole process --> Same issue. 

I had a friend try to push the same application on his account and it works just fine. This suggests to me that there is something wrong with the creation of accounts. 

I hope you are able to help me.

**Comment by agracey** [comment]
We seem to be experiencing some system instability but not any that should affect this. 

Thank you for the heads up, I'll look at it when back at work next week.

**Comment by marcus-nl** [comment]
I have the same issue, but with an existing account and applications that worked before. 

One application failed after a redeployment, and the other spontaneously (IIRC), both with the same error message as @edwin-hendriks mentioned:

`404 Not Found: Requested route ('...') does not exist.`

**Comment by agracey** [comment]
Should be working again after I kicked it. Looking into why this happened.

**Comment by marcus-nl** [comment]
Works again for me indeed! Thanks!
