### ISSUE TITLE
wrong certificate 

### ISSUE THREAD

**Issue by lnyiri63** [SUSE-Developer-Community/explore.suse.dev#73]
Hi,
on published refference link to developer sandbox getting started guide (link is on page https://developer.suse.com/capsandbox/ ) 
![image](https://user-images.githubusercontent.com/52237953/113147446-11865080-9231-11eb-85e1-03bcde49ba30.png)
Please use certificate from trusted publishers, there are some free of charge too. 

Thanks

Ladislav

**Comment by lnyiri63** [comment]
And using HSTS makes this more strange.

**Comment by agracey** [comment]
Looks like we had a node failure. Should be back up now
